### ISSUE TITLE
Download files from dataset

### ISSUE THREAD

**Issue by pastewka** [IMTEK-Simulation/dtool-lookup-gui#12]
It would be useful to have partial downloads of dataset, i.e. double clicking a file opens it.

**Comment by pastewka** [comment]
I've implemented basic download functionality. There are a couple of issue I would like to discuss:

1. The local data sources must have exactly the same name as the data sources on the lookup server. I think this is a reasonable requirement.
2. Right now, the GUI opens the file it obtains from `item_content_abspath`. On Linux, this is the file in the dtool cache directory `.dtool/cache`. This has several issues: a) the file is not read only and may be modified, essentially creating a cache that is not in sync with the data set, b) the file names are UUIDs which may confuse the user

To mitigate 2., it may be necessary to copy the file to a second location before opening it. Potentially, that location should be configurable in the GUI. My suggestion is to provide a basic path `<root>`, files are then copied to `<root>/<dataset-uuid>/<filename>`. Files are only copied when they are opened and they are not copied when the file exists. The dataset directory must be the UUID because dataset names are not unique. Item names within a dataset are unique, thus we can use the normal filename (rather than the item's UUID that is in the cache).

What do you thing @AntoineSIMTEK @wgnoehring @jotelha

**Comment by AntoineSIMTEK** [comment]
I don't understand 1

2a): Are you sure this is a problem ? I am quite sure dtool communicates with the server at each access to the data, even if it is already cached. I thought part of the purpose was to verify the integrity of the data. 

2b) Yes I think it would be good to have a human readable name.
I like your solution. I would for example use the download folder as `<root>`.
