### ISSUE TITLE
regex in queries don't always work

### ISSUE THREAD

**Issue by AntoineSIMTEK** [IMTEK-Simulation/dtool-lookup-gui#21]
{"name": {"$regex":r"^polynom3_constrange_\w+"}}

works when using directly the lookup API but not in the field of the lookup gui. 

I guess there is somethinng weird going on with special characters.

**Comment by jotelha** [comment]
The preceeding r is valid Python only, I am quite sure that this renders the query unparsable

**Comment by AntoineSIMTEK** [comment]
So I need to escape stuff by hand : the following works: 

`{"name": {"$regex":"^polynom3_constrange_\\w+"}}`

My problem is that since I do not know what is running behind the gui I don't know which syntax is expected.
In the future of the GUI some hints will be welcome.

Thanks for the help, I close this issue now.
