### ISSUE TITLE
Report errors to user

### ISSUE THREAD

**Issue by pastewka** [IMTEK-Simulation/dtool-lookup-gui#4]
Error (exceptions) are currently shown in the terminal, but they should be properly reported to the user.

**Comment by pastewka** [comment]
A first partial implementation of this is in 3f90233128cc53a22a056a7a61584591ce941d80.

**Comment by pastewka** [comment]
We now have a log window and a little popup reporting errors

**Comment by jotelha** [comment]
Then let's close this issue
