### ISSUE TITLE
Don't display overboarding exceptions in full in the error msg line, ...

### ISSUE THREAD

**Issue by jotelha** [IMTEK-Simulation/dtool-lookup-gui#46]
.. like this one, 
![image](https://user-images.githubusercontent.com/1868344/144998364-0ae277f6-e9b0-497e-b8ee-afea3edd4532.png)

Maybe introduce dedicated debug message log window?

**Comment by pastewka** [comment]
Has this been fixed by #48?

**Comment by jotelha** [comment]
It's fixed by 233af3374e465f6a81e5032d62e0b65272db480d
