### ISSUE TITLE
GUI is lame because it loads 10000 datasets

### ISSUE THREAD

**Issue by AntoineSIMTEK** [IMTEK-Simulation/dtool-lookup-gui#61]
I am using the legacy version (without all the buttons to move datasets around) but I think this problem exists as well in the current version.

Because the GUI loads all 10000 datasets by default, it takes a lot time for it to be responsive at all.

Since at the end of the day, I am most of the time only interested in my own datasets, what about putting a default query in an environment variable or config file ? Like {"readme.owner.name": "Antoine Sanner"}

**Comment by AntoineSIMTEK** [comment]
Here is a quick fix: 

https://github.com/IMTEK-Simulation/dtool-lookup-gui/commit/60810bfe8ad3a08ded5600e7f1ac95e171bb1a5d


I have put a file in `~/.config/dtool/default_query.txt` 
with for example
```
{"$and":[{"readme.owners.name":{"$eq":"Antoine Sanner"}},
{"readme.creation_date":{"$gt": "2022-01-03"}}
]}
```

**Comment by jotelha** [comment]
The current version only loads 100 datasets (in the lookup server tab). Configuring a default query is a good idea anyway, I think we can put that in the settings at some point.

**Comment by AntoineSIMTEK** [comment]
Ok. So that is a good argument for me to move to the new version.
