### ISSUE TITLE
search in specific fields and make logical constructs

### ISSUE THREAD

**Issue by AntoineSIMTEK** [IMTEK-Simulation/dtool-lookup-gui#8]

**Comment by jotelha** [comment]
https://github.com/IMTEK-Simulation/dtool-gui/commit/e9c7fc20c70cf3be41d5bd06895008690eb9e748 

will forward mongo syntax queries encapsulated between { and } directly to the server.

The accompanying modification to the lookup server

https://github.com/jotelha/dtool-lookup-server/commit/d9502a9941829fe88cabdb2a59124a70b379c8d8

will relax the keyword filtering and allow pretty much any query to be processed. Some convenient operators make life easier, i.e.  searching with regular expressions, such as `{"name":{"$regex":"n-([12][0-9]+)-m-\\1-gromacsnvt"}}`:

![image](https://user-images.githubusercontent.com/1868344/92015391-fd3cac80-ed50-11ea-8d33-3cc72f79c16b.png)

What makes this change really useful: Next to a few top-level fields (see https://github.com/jic-dtool/dtool-lookup-server/blob/d4dba7317c15493239411e0a3af2eb7e0e434edf/dtool_lookup_server/utils.py#L28-L40) the lookup server has the whole README parsed and stored below the top-level `readme` field, thus arbitrary queries on metadata are possible, i.e. `{"readme.system.surfactant.name":{"$in":["SDS","CTAB"]}, "readme.system.surfactant.nmolecules":{"$gt": 100, "$lt": 150}}`:

![image](https://user-images.githubusercontent.com/1868344/92017160-a5ec0b80-ed53-11ea-9323-5b3c4e981772.png)

For an introduction into this NoSQL syntax, I recommend the materials project workshop's primer at https://github.com/materialsproject/workshop/tree/master/workshop/primer. 

The server-side modifications would render all per-user permissions configured outside of the MongoDB ineffective. Anything within the database is queryable by any user.  In our current mode of operation, that is the desired case anyway, thus I would not be worried about that. On the long term, it might be a good idea to allow direct access to the lookup server's underlying mongodb (and have the user permissions maintained at db level), as it is easy to formulate and submit such queries as nested dicts and lists directly via Python and pymongo.

The two modifications in client and server must go together. I have a testing instance with the modified server running at ports 5100 and 5101 of simdata.uni-freiburg.de to try them out. Other than the ports, access configuration is the same as for the "production" system.

**Comment by AntoineSIMTEK** [comment]
Awesome thank you !

**Comment by AntoineSIMTEK** [comment]
Can this actually be merged in master ?

**Comment by pastewka** [comment]
@jotelha can we close this issue?

**Comment by jotelha** [comment]
Yes
